# Configuration
import pandas as pd

configfile: "config.yaml"
metadata_file = config["input_meta"]
metadata = pd.read_csv(metadata_file, sep="\t")
samples = metadata["sample"].tolist()

# Helper function to retrieve file paths from metadata
def get_file(sample, column):
    file_path = metadata.loc[metadata["sample"] == sample, column].values[0]
    return file_path if pd.notna(file_path) else None

# Rule all: Entry point for the workflow
#rule all:
#    input:
#        expand("output/final_vcfs/{sample}_final.txt", sample=samples)

rule all:
    input:
        #expand("output/evaluated_solutions/{sample}_evaluated_solutions.txt", sample=samples)
        expand("output/clonal_multiplicities/{sample}_multiplicities.txt", sample=samples)
#        "output/mutation_signature_matrix_state.csv",
#        expand("output/reassigned_signatures/{sample}_reassigned_signatures.csv", sample=samples) 


# 1. Preprocessing steps
rule trim:
    input:
        snv_file=lambda wildcards: get_file(wildcards.sample, "snv"),
        cnv_file=lambda wildcards: get_file(wildcards.sample, "cnv"),
        purity_file=config["purity_file"]
    output:
        trim_file="output/trim/{sample}_trim.txt"
    resources:
        mem_mb=2000,
        time="15:00"
    conda:
        "tau"
    shell:
        "python scripts/trim.py {wildcards.sample} {input.snv_file} {input.cnv_file} {output.trim_file} {input.purity_file}"

rule categorize:
    input:
        trim_file="output/trim/{sample}_trim.txt"
    output:
        categorize_file="output/categorize/{sample}_categorize.txt"
    resources:
        mem_mb= lambda wildcards, attempt: 3000 * attempt,
        time="30:00"
    conda:
        "tau"
    shell:
        "python scripts/categorize.py {wildcards.sample} {input.trim_file} {output.categorize_file}"

rule revise:
    input:
        categorize_file="output/categorize/{sample}_categorize.txt"
    output:
        revise_file="output/revise/{sample}_revise.txt"
    resources:
        mem_mb= lambda wildcards, attempt: 30000 * attempt,
        time="30:00"
    conda:
        "tau"
    shell:
        "Rscript scripts/revise.R {input.categorize_file} {output.revise_file} {wildcards.sample}"

rule normalize:
    input:
        revise_file="output/revise/{sample}_revise.txt"
    output:
        normalize_file="output/normalize/{sample}_normalize.txt"
    resources:
        mem_mb=1000,
        time="30:00"
    conda:
        "tau"
    shell:
        "Rscript scripts/normalize.R {input.revise_file} {output.normalize_file}"

rule annotate_vcf:
    input:
        normalize_file="output/normalize/{sample}_normalize.txt",
        vcf_file=lambda wildcards: get_file(wildcards.sample, "snv")
    output:
        vcf="output/annotate_vcf/{sample}.vcf"
    resources:
        mem_mb=2000,
        time="30:00"
    conda:
        "tau"
    shell:
        "Rscript scripts/annotate_vcf.R {wildcards.sample} {input.normalize_file} {input.vcf_file} {output.vcf}"

#Signature likelihood calculation
rule calculate_likelihoods:
    input:
        normalize_file="output/normalize/{sample}_normalize.txt",
        exposure_file=config["exposure_file"],
        signature_file=config["signature_file"]
    output:
        likelihood_file="output/sig_likelihood_sample/{sample}_likelihood.txt"
    conda:
        "tau"
    resources:
        mem_mb= lambda wildcards, attempt: 2000 * attempt,
        time="20:00"
    shell:
        """
        python scripts/calculate_likelihoods.py \
            --normalize_file {input.normalize_file} \
            --exposure {input.exposure_file} \
            --signature {input.signature_file} \
            --output {output.likelihood_file}
        """

rule calculate_clonal_multiplicities:
    input:
        likelihood="output/sig_likelihood_sample/{sample}_likelihood.txt"
    output:
        multiplicities="output/clonal_multiplicities/{sample}_multiplicities.txt"
    shell:
        """
        python scripts/calculate_clonal_multiplicities.py --input {input.likelihood} --output {output.multiplicities}
        """

#rule evaluate_solutions:
#    input:
#        multiplicities="output/clonal_multiplicities/{sample}_multiplicities.txt",
#        solution_file="all_solution_file.txt"
#    output:
#        evaluated_solutions="output/evaluated_solutions/{sample}_evaluated_solutions.txt"
#    shell:
#        """
#        python scripts/evaluate_solutions.py --multiplicities {input.multiplicities} --solutions {input.solution_file} --output {output.evaluated_solutions}
#        """
## Mutation signature matrix
#rule make_mut_sig_matrix:
#    input:
#        likelihood_files=expand("output/likelihoods/{sample}_likelihoods.txt", sample=samples)
#    output:
#        matrix_state="output/mutation_signature_matrix_state.csv"
#    conda:
#        "tau"
#    shell:
#        "python scripts/make_mut_sig_matrix.py {input.likelihood_files} {output.matrix_state}"
#
## Reassign signatures
#rule reassign_signatures:
#    input:
#        matrix_state="output/mutation_signature_matrix_state.csv",
#        exposure_file=config["exposure_file"],
#        catalog_file=config["signature_file"]
#    output:
#        expand("output/reassigned_signatures/{sample}_reassigned_signatures.csv", sample=samples)
#    conda:
#        "tau"
#    shell:
#        """
#        python scripts/reassign_signatures.py \
#            --matrix_state {input.matrix_state} \
#            --exposure_file {input.exposure_file} \
#            --catalog_file {input.catalog_file} \
#            --output_dir output/reassigned_signatures
#        """
